### PR TITLE
22 improve resilience

### LINKED ISSUE #22: Improve proxy resilience
Sometimes the upstream calls to save instance logs take quite a long time. This will in the worst case lead to "504 Gateway Timeout" in the load balancer.

Possible fix: Return immediately and process the request asynchronously. (Need to figure out, what Spring Cloud Netflix offers here)

### PR DESCRIPTION
**Pull request by harti2006**
fixes #22 

## Implemented strategy

* removed Zuul proxy in favor of a manual implementation
* log handling is now asynchronous
    * Taupage instance get their answer immediately
* retry is implemented (max 3 times with exponential backoff: 1s, 5s, 25s)

### CODE REVIEW

**Comment by harti2006** [comment]
Hystrix is missing in this implementation! But it didn't work before either.

**Comment by harti2006** [comment]
:+1:

**Comment by ChristianLohmann** [comment]
👍

**Comment by prayerslayer** [comment]
testfoo

On 16 June 2016 at 13:53, Christian Lohmann <notifications@github.com>
wrote:

> 👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zalando-stups/log-sink/pull/24#issuecomment-226463576>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA1nsEguOvpSvb3K76OkfuPH668DCsD6ks5qMTkggaJpZM4IzA5K>
> .
>



-- 

undefined = () => {}


*         (  .      )
        )           (              )
              .  '   .   '  .  '  .
     (    , )       (.   )  (   ',    )
      .' ) ( . )    ,  ( ,     )   ( .
   ). , ( .   (  ) ( , ')  .' (  ,    )     Nikolaus Piccolotto
  (_,) . ), ) _) _,')  (, ) '. )  ,. (' )    *sets stuff on fire*
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ *

**Comment by ChristianLohmann** [comment]
👍

**Comment by prayerslayer** [comment]
👍

**Comment by taojang** [comment]
Ah, I'm too late

**Comment by prayerslayer** [comment]
You can still put your thumbs up 😉

**Pull request merged**
